baseURL: https://victoria.dev/
languageCode: en-us
title: victoria.dev
theme: memex
pygmentsCodeFences: true
pygmentsUseClasses: true
assetDir: themes/memex/static

taxonomies:
  series: series
  tag: tags

permalinks:
  blog: :section/:title

enableGitInfo: true

author:
  name: Victoria Drake
  image: img/victoria_headshot.jpg
  about: Victoria Drake is an experienced software engineer with a background in technical and executive leadership.
  email: hello@victoria.dev
  domain: https://victoria.dev

params:
  logo: img/logo.png
  dateFormat: January 2, 2006
  dateTime: "02 Jan 2006 15:04 MST"
  # customCSS: css/style.css # relative to ./static/
  webmentionUrl: https://webmention.io/victoria.dev/webmention
  pingbackUrl: https://webmention.io/victoria.dev/xmlrpc
  # micropubUrl: https://example.com/.netlify/functions/micropub
  # microsubUrl: https://aperture.p3k.io/microsub/example
  # For IndieAuth
  githubuser: victoriadrake
  twitteruser: victoriadotdev
  mastodon: https://mastodon.technology/@victoria
  monetization: $ilp.uphold.com/pBRfRwg2EJAe
  subscribeLink: https://api.victoria.dev/subscribe/
  mainSections:
    - blog
    - neofeed
  rssTitle: Victoria Drake's Blog
  rssDescription: Get the latest posts from Victoria Drake.

menu:
  main:
    - name: hello
      url: /
      pre: "<img src='/icon/bookmark.svg' alt='home page icon' height='18px' class='filter-icon'>"
      weight: 1
    - name: blog
      identifier: blog
      url: /blog/
      pre: "<img src='/icon/quote.svg' alt='blog icon' height='18px' class='filter-icon'>"
      weight: 3
    - name: about
      identifier: about
      url: /about/
      pre: "<img src='/icon/profile.svg' alt='about page icon' height='18px' class='filter-icon'>"
      weight: 2
    # - name: bookshelf
    #   identifier: bookshelf
    #   url: /bookshelf/
    #   pre: "<img src='/icon/book.svg' alt='bookshelf icon' height='18px' class='filter-icon'>"
    #   weight: 4
  fourohfour:
    - name: home
      url: /
    - name: valley of floating windows
      url: /neofeed
    - name: blogland
      url: /blog
    - name: colorful horizontal hills
      url: /tags
  home:
    - name: blog
      identifier: blog
      url: /blog/
      post: "-"
    - name: about
      identifier: about
      url: /about/
      post: "-"
    - name: github
      identifier: github
      url: https://github.com/victoriadrake
      post: "-"
    - name: neofeed
      identifier: neofeed
      url: /neofeed/

mediaTypes:
  "application/atom+xml":
    suffixes:
      - "xml"

outputFormats:
  EMAIL:
    name: "Email"
    mediaType: "application/rss+xml"
  Json:
    name: "Json"
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: false
    rel: "alternate"
    isHTML: false
    permalinkable: false
  Atom:
    name: "Atom"
    mediaType: "application/atom+xml"
    baseName: "atom"
    isPlainText: false
    rel: "alternate"
    isHTML: false
    permalinkable: false

outputs:
  home:
    - HTML
    - ATOM
    - JSON
    - RSS
  page:
    - HTML
  blog:
    - HTML
    - ATOM
    - RSS
    - EMAIL
  section:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
  term:
    - HTML
    - ATOM
    - JSON
    - RSS
  wc:
    - RSS

markup:
  goldmark:
    renderer:
      unsafe: true


related:
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold: 80
  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer: true
  # Will lower case keywords in both queries and in the indexes.
  toLower: false
  indices:
    - name: "keywords"
      weight: 100
    - name: "author"
      toLower: true
      weight: 10
    - name: "tags"
      weight: 150
    - name: "date"
      weight: 10
      pattern: "2006"
