name = "Study"
license = "MIT"
licenselink = "https://github.com/victoriadrake/victoriadrake.github.io/blob/main/LICENSE"
description = "A cozy, text-based theme inspired by a mid-century study with leather chairs, rich woods, and green plants"
homepage = "https://victoria.dev/"
tags = ["blog", "responsive", "personal", "light", "dark", "minimal", "clean"]
features = ["responsive", "dark mode", "search", "microformats", "indieweb", "seo"]
min_version = "0.80.0"

[author]
  name = "Victoria Drake"
  homepage = "https://victoria.dev/"
