baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Awesome Website"
theme = "bluf"
paginate = 10

[params]
  description = "A compelling few words"
  headline = "A stunning headline"
  subheadline = "Some more compelling words. Maybe even a sentence."

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/posts/:slug/"
