baseURL = "https://example.com/"
languageCode = "en-us"
title = "Victoria Drake"
theme = "victoria"
paginate = 10

[params]
  description = "Director of Engineering • Technical Writer • Open Source Contributor"
  headline = "Victoria Drake"
  subheadline = "Building better software teams through thoughtful leadership and clean code"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/posts/:slug/"
