name = "BLUF"
license = "MIT"
licenselink = "https://github.com/victoriadrake/victoriadrake.github.io/tree/master/themes/bluf/LICENSE"
description = "A brutalist typography-driven Hugo theme"
homepage = "https://github.com/victoriadrake/victoriadrake.github.io/blob/master/themes/bluf/"
tags = ["blog", "minimal", "modern", "typography"]
features = ["responsive", "fast", "clean"]
min_version = "0.84.0"

[author]
  name = "Victoria Drake"
  homepage = "https://victoria.dev"
