name: Deploy

on:
  schedule:
    - cron: '42 13 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master and get private submodules
        uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: 1
          token: ${{ secrets.PTOKEN }}
      - name: Install latest Hugo
        run: |
          sudo apt-get install jq
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          curl -sSL "https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION:1}_linux-amd64.deb" -o hugo.deb
          sudo dpkg -i hugo.deb
          hugo version
      - name: Build site
        run: |
          git pull --recurse-submodules
          hugo --minify --cleanDestinationDir
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
