name: Deploy

on:
  schedule:
    - cron: '42 13 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master and get private submodules
        uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: 1
          token: ${{ secrets.PTOKEN }}
      - name: Install latest Hugo
        run: |
          mkdir tmp/ && cd tmp/
          curl -sSL $(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*\hugo_extended.*\_Linux-64bit.tar.gz" | rev | cut -d ' ' -f 1 | rev | tr -d '"') | tar -xvzf-
          sudo mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/
          hugo version
      - name: Build site
        run: |
          git pull --recurse-submodules
          hugo --minify --cleanDestinationDir
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
